### PR TITLE
Fixed issues with fetching related audio items

### PR DESCRIPTION
**Pull request by adamshin**

### CODE REVIEW

**Comment by hiltonc** [comment]
It didn't pass tests though

**Comment by brandenr** [comment]
Yeah, I'm sorry. I realized after that this isn't GL's content branch... I was thinking it was expected for it to fail tests

**Comment by brandenr** [comment]
Same failure happens with this reverted: https://github.com/CrossWaterBridge/LDSContent/pull/20

**Comment by hiltonc** [comment]
Let's just fix this on the next PR and move forward then

**Comment by hiltonc** [comment]
@adamshin will you add a unit test to support this change?

**Comment by nickmshelley** [comment]
@hiltonc I think the plan was to get the content branch working with GL and then make a pull-request into master, at which point we'd fix any breaking tests and probably add new ones (since Stephan and I have been committing directly to this content branch without review or tests).

But yeah, it couldn't hurt to get a head start.

**Comment by hiltonc** [comment]
My bad, I didn't realize this wasn't master. Carry on.

**Comment by hiltonc** [comment]
Don't think for a second that GL working with this branch will give it a pass on code review when merging into master though ;)

**Comment by nickmshelley** [comment]
I did think that, but only for .95 seconds.

**Pull request merged**
