### PR TITLE
Leave unmerged catalogs compressed to save disk space

### PR DESCRIPTION
**Pull request by stephanheilner**

### CODE REVIEW

**Comment by hiltonc** [comment]
With this change, the app will need to download all catalogs prior to merging each time, even if only one of them has changed, is that the intent?

**Comment by stephanheilner** [comment]
Definitely not. But I don't see how this change does that. I was trying to understand how catalog updates/merged work. What did I miss?

**Comment by hiltonc** [comment]
I might have misunderstood, let me look again.

**Comment by hiltonc** [comment]
OK, I get it. Nice!

**Comment by stephanheilner** [comment]
The default catalog is 50mb unzipped, 12mb zipped, so this should hopefully cut down a little on the bloat size of the app. Right now, the app code is about 120mb, the catalog is 50mb (x2 because of the merged version), and then item packages about another ~100mb. This will only cut it down by about 40mb, but at least its something, right?

**Comment by hiltonc** [comment]
We should consider complicating things with language-specific catalogs.

**Comment by stephanheilner** [comment]
I really, really like that idea! Jeff and I have been talking about that lately.

**Pull request merged**
