### PR TITLE
Added maxSubitemMetadataID func for packager

### PR DESCRIPTION
**Pull request by stephanheilner**
* Also handle unused result warnings until https://bugs.swift.org/browse/SR-1681 is fixed.

### CODE REVIEW

**Comment by hiltonc** [comment]
The code looks fine, but it seems a little odd to expose `maxSubitemMetadataID`... can you show the code that uses it?

**Comment by stephanheilner** [comment]
All tests pass locally.

**Comment by stephanheilner** [comment]
Sure, in Packager, when we resume (after it having crashed while running), we have a local var that we increment for the subitemmetadata id so that its unique across all subitems.
```swift
var nextSubitemMetadataID: Int64 = 1
catalog.schemaVersion = Catalog.SchemaVersion
        if nextSubitemMetadataID == 1 {
            nextSubitemMetadataID = catalog.maxSubitemMetadataID() + 1
        }  
```

**Comment by stephanheilner** [comment]
Test still pass locally as well. I'll merge now and work on travis later if that doesn't pass.

**Pull request merged**
