### PR TITLE
Rename library_item & library_collection column to title_html

### PR DESCRIPTION
**Pull request by stephanheilner**

### CODE REVIEW

**Comment by stephanheilner** [comment]
This will fail until we run GLContentPackager with the change.

**Comment by toddbohman** [comment]
Windows developer here.  In the future, can we be sure to communicate breaking schema changes?  This change broke our app.

Here are a couple of proposals
1. Rev the schema version if there are breaking changes (column/table renames, dropped columns/tables).  That way we can put in some code in our app to ensure we don't update to catalogs we don't understand.
2. Since we are in BETA, and breaking changes are expected, can we at least send out a mail to the consumers of the HTML5 content when we change the schema?

Thanks,
Todd Bohman

**Comment by nickmshelley** [comment]
@toddbohman All the open source libraries I've used communicate breaking changes by doing a major version bump when they have their next official release. The master branch is usually used as a development branch and has no backwards compatibility guarantees.

Since this project is being developed similar to other open source projects, if you're worried about your code not breaking, I'd stick to the latest official release: https://github.com/CrossWaterBridge/LDSContent/releases/tag/1.1.1. Since there have been many backwards-incompatible changes, I'm certain the next release will have a major version bump to 2.0.0, which will provide the communication you desire.

**Comment by nickmshelley** [comment]
Oh, I just realized you were talking about the content that this project consumes, not the project itself. So maybe ignore my comment. 😄

**Comment by stephanheilner** [comment]
Now that prod and beta are in sync, except for when we make scheme changes, we should all start using the prod content. That will allow us to make these kind of changes, and to coordinate when we push them to prod.

**Comment by toddbohman** [comment]
@nickmshelley Ok, nice distinction.  As a developer for the Windows app, my concern is with the content produced by this library, not the library itself.

@stephanheilner So should we switch to use the production endpoint on our beta app?  Is this the direction given to the Android folks as well? Is that what iOS is going to do as well?  Are the annotation docmaps ready for the switch?  What annotation endpoint should we use (BETA or PROD)?  Last I heard, Craig Tebbs was saying that we should be using the BETA endpoint, but I don't know if that maps properly to the prod content.

So if I understand the given guidance.  We should be pushing out a BETA app with content pointed at production and annotations likely pointed at BETA?  Then for development, we can point to beta to get immediate changes with the assumption that content created on production will have a schema version revved to indicate breaking changes?

I hope I'm not coming across as critical, just trying to find a way to ensure other consumers of the content can safely plug into the pipeline with as few issues as possible. :)

**Pull request merged**
