### PR TITLE
Added author image renditions field to author table

### PR DESCRIPTION
**Pull request by stephanheilner**

### CODE REVIEW

**Comment by hiltonc** [comment]
Don't images come from Telescope? There should be an array of URLs + sizes.

**Comment by stephanheilner** [comment]
I didn't see any telescope ids in the LDS:meta, but I can check again. This is more of a personal interest of mine. :) It would be super nice to have images for authors for a little side-thing I'm working on.

**Comment by hiltonc** [comment]
We should totally have this, for GL AND personal projects :). Let's see if we can have them put the telescope ID, Scott knows better than to just put a single image URL.

**Comment by hiltonc** [comment]
Can you give the URI of a file that has an author image URL? I'm looking at /general-conference/2015/10/a-plea-to-my-sisters, which has a headshot image in the body, but no image URL in the lds:meta.

**Comment by stephanheilner** [comment]
So that's the problem. The <lds:meta only has an author URI. The URI contains an <img with a @class of 'go-bio__image', which is their headshot image. I'll see if Scott could include a telescope ID in there as well, that would be so much better! If we only include the URL, any clients that use the app, will have to take the uri `/church/leader/henry-b-eyring`, and then add `https://www.lds.org` to it, then parse the HTML for the image to get: 
`https://www.lds.org/bc/content/shared/content/images/leaders/henry-b-eyring-large.jpg`

**Comment by stephanheilner** [comment]
So, @hiltonc, what do you think of this change? Ok, or should I make some changes?

**Comment by hiltonc** [comment]
Would you be OK with changing it so that it stores the image as "image_renditions" with just a single image URL + size?

**Comment by stephanheilner** [comment]
Sure, on it.

**Comment by hiltonc** [comment]
👍

**Pull request merged**
